version: '2'

services:
  web:
    image: slickframework/nginx
    ports:
      - 8880:80
    volumes_from:
      - php
    environment:
      - CONF_APP=slick
      - CONF_PUBLIC=webroot
      - CONF_UPSTREAM=php:9000

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=slick_users
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  php:
    image: slickframework/php:5.5
    environment:
      - USE_XDEBUG=yes
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db
      - mail

  mail:
    image: helder/mailcatcher
    ports:
      - 1080:80

  gulp:
    image: helder/node
    volumes:
      - ./webroot:/data
    command: /bin/true