version: '2'
services:
  mongo:
    image: "mongo:3"

  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"

  graylog:
    image: graylog2/server:2.1.0-3
    environment:
      GRAYLOG_PASSWORD_SECRET: justAnotherSecrect
      GRAYLOG_ROOT_PASSWORD_SHA2: 2a97516c354b68848cdbd8f54a226a0a55b21ed138e207ad6c5cbb9c00aa5aea
      GRAYLOG_ENDPOINT_URI: http://127.0.0.1:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"

  php:
    depends_on:
      - db
      - graylog